# Generated by Django 3.1.7 on 2021-04-02 15:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeData',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('experience', models.TextField(blank=True)),
                ('projects', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'ResumeData',
            },
        ),
    ]
