# Generated by Django 3.1.7 on 2021-04-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0002_auto_20210405_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumedata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='resumedata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resumedata',
            name='skills',
        ),
        migrations.AddField(
            model_name='resumedata',
            name='file_path',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
